---
net:
  # The network device of the management interface
  management_interface: "ens2.200"
  # This config is for a single controller setup
  controller:
    ip: "10.0.0.11"
    hostname: "controller"
  # For the /etc/hosts config so each node can communicate with each other  
  hosts: [
    {
      ip: "10.0.0.21",
      hostname: "compute1"
    },
    {
      ip: "10.0.0.22",
      hostname: "compute2"
    },
    {
      ip: "10.0.0.23",
      hostname: "compute3"
    }
  ]
  # The storage_devices are mount points on the object nodes
  object_nodes: [
    {
      ip: "10.0.0.21",
      storage_devices: [
        {
          name: "sda"
        }
      ]
    },
    {
      ip: "10.0.0.22",
      storage_devices: [
        {
          name: "sda"
        }
      ]
    },
    {
      ip: "10.0.0.23",
      storage_devices: [
        {
          name: "sda"
        }
      ]
    }
  ]
# Secrets for OpenStack services. Keep them safe
db:
  pass: ""
rabbit:
  pass: RABBIT_PASS
horizon:
  allowed: "'*'"
  pass: HORIZON_PASS
keystone:
  db: KEYSTONE_DBPASS
  admin: ADMIN_PASS
glance:
  db: GLANCE_DBPASS
  user: GLANCE_PASS
placement:
  db: PLACEMENT_DBPASS
  user: PLACEMENT_PASS
nova:
  db: NOVA_DBPASS
  user: NOVA_PASS
neutron:
  db: NEUTRON_DBPASS
  user: NEUTRON_PASS
swift:
  user: SWIFT_PASS
  prefix: HASH_PATH_PREFIX
  sufix: HASH_PATH_SUFFIX 
metadata:
  pass: METADATA_SECRET
