---
- hosts: all

  vars_files:
    - vars/service-selection.yml
    - vars/config.yml
    - vars/secrets.yml

  environment:
    - OS_PROJECT_DOMAIN_NAME: default
    - OS_USER_DOMAIN_NAME: default
    - OS_PROJECT_NAME: admin
    - OS_USERNAME: admin
    - OS_PASSWORD: "{{ keystone['admin'] }}"
    - OS_AUTH_URL: http://{{ net['controller']['hostname'] }}:5000/v3/
    - OS_IDENTITY_API_VERSION: 3
    - OS_IMAGE_API_VERSION: 2

  tasks:
    - name: Prepare Openstack
      import_role:
        name: prepare

    - name: Install misc services for Openstack
      import_role:
        name: misc
      when: inventory_hostname in groups["controll"]

    - name: Install keystone
      import_role:
        name: keystone
      when:
        - inventory_hostname in groups["controll"]
        - 'keystone_service|bool'

    - name: Install glance
      import_role:
        name: glance
      when:
        - inventory_hostname in groups["controll"]
        - 'glance_service|bool'

    - name: Install nova on controller
      import_role:
        name: nova_controller
      when:
        - inventory_hostname in groups["controll"]
        - 'nova_service|bool'

    - name: Install nova on compute nodes
      import_role:
        name: nova_compute
      when:
        - inventory_hostname in groups["compute"]
        - 'nova_service|bool'

    - name: Install neutron on controller
      import_role:
        name: neutron_controller
      when:
        - inventory_hostname in groups["controll"]
        - 'neutron_service|bool'

    - name: Install neutron on compute nodes
      import_role:
        name: neutron_compute
      when:
        - inventory_hostname in groups["compute"]
        - 'neutron_service|bool'

    - name: Install swift proxy on controller
      import_role:
        name: swift_proxy
      when:
        - inventory_hostname in groups["controll"]
        - 'swift_service|bool'

    - name: Install swift on object nodes
      import_role:
        name: swift_object
      when:
        - inventory_hostname in groups["object"]
        - 'swift_service|bool'

    - name: Create rings for account, container and object (Swift)
      import_role:
        name: swift_rings
      when:
        - inventory_hostname in groups["controll"]
        - 'swift_service|bool'

    - name: Finalize swift on controller and object nodes
      import_role:
        name: swift_all_nodes
      when:
        - inventory_hostname in groups["controll"] or inventory_hostname in groups["object"]
        - 'swift_service|bool'

    - name: Install cinder on controller
      import_role:
        name: cinder_controller
      when:
        - inventory_hostname in groups["controll"]
        - 'cinder_service|bool'

    - name: Install cinder on block nodes
      import_role:
        name: cinder_block
      when:
        - inventory_hostname in groups["block"]
        - 'cinder_service|bool'

    - name: Configure cinder on compute nodes
      import_role:
        name: cinder_compute
      when:
        - inventory_hostname in groups["compute"]
        - 'cinder_service|bool'

    - name: Install barbican on controller
      import_role:
        name: barbican_controller
      when:
        - inventory_hostname in groups["controll"]
        - 'barbican_service|bool'

    - name: Install trove on controller
      import_role:
        name: trove_controller
      when:
        - inventory_hostname in groups["controll"]
        - 'trove_service|bool'

    - name: Install horizon
      import_role:
        name: horizon
      when:
        - inventory_hostname in groups["controll"]
        - 'horizon_service|bool'
