---
- name: Install keystone package
  become: true
  package:
    name: 
      - openstack-neutron-linuxbridge
      - ebtables
      - ipset
    state: present

- name: Set variables with Jinja and copy neutron.conf
  become: true
  template:
    src: neutron.conf.j2
    dest: /etc/neutron/neutron.conf
    owner: root
    group: neutron
    mode: "0640"

- name: Set variables with Jinja and copy linuxbridge_agent.ini
  become: true
  template:
    src: linuxbridge_agent.ini.j2
    dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
    owner: root
    group: neutron
    mode: "0640"

- name: Enable network bridge for neutron ml2 plugin
  become: true
  shell: |
    echo "net.bridge.bridge-nf-call-iptables = 1
    net.bridge.bridge-nf-call-ip6tables = 1" >> /etc/sysctl.conf 

- name: Restart nova-compute service
  become: true
  systemd:
    name: openstack-nova-compute.service
    state: restarted

- name: Enables and starts nova services
  become: true
  systemd:
    name: neutron-linuxbridge-agent.service
    enabled: yes
    state: started