---
- name: Install rsync package
  become: true
  package:
    name: rsync-daemon
    state: present

- name: Set variables with Jinja and copy rsyncd.conf
  become: true
  template:
    src: rsyncd.conf.j2
    dest: /etc/rsyncd.conf
    owner: root
    group: root
    mode: "0644"

- name: Enable and start rsyncd service
  become: true
  systemd:
    name: rsyncd.service
    enabled: yes
    state: started

- name: Install swift packages
  become: true
  package:
    name: 
      - openstack-swift-account 
      - openstack-swift-container
      - openstack-swift-object
    state: present

- name: Set variables with Jinja and copy account-server.conf
  become: true
  template:
    src: account-server.conf.j2
    dest: /etc/swift/account-server.conf
    owner: root
    group: swift
    mode: "0644"

- name: Set variables with Jinja and copy container-server.conf
  become: true
  template:
    src: container-server.conf.j2
    dest: /etc/swift/container-server.conf
    owner: root
    group: swift
    mode: "0644"

- name: Set variables with Jinja and copy object-server.conf
  become: true
  template:
    src: object-server.conf.j2
    dest: /etc/swift/object-server.conf
    owner: root
    group: swift
    mode: "0644"

- name: Create directory for swift cache
  become: true
  file:
    path: /var/cache/swift
    recurse: true
    state: directory
    owner: swift
    group: swift
    mode: "0755"

- name: Change permissions for /srv/node directory
  become: true
  file:
    path: /srv/node
    recurse: true
    state: directory
    owner: swift
    group: swift

- name: Open 6200, 6201 and 6202 TCP ports
  become: true
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop: 
    - 6200/tcp
    - 6201/tcp
    - 6202/tcp
